name: tank_mates
description: An aquarium compatibility app.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_spinkit: ^4.1.1+1
  provider: ^4.0.3
  intl: ^0.16.1
  moor: ^2.4.1
  moor_ffi: ^0.4.0
  path_provider: ^1.6.4
  path: ^1.6.4
  flutter_slidable: ^0.5.3
  shared_preferences: ^0.5.6+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^2.4.0
  build_runner: ^1.7.4

flutter:
  uses-material-design: true

  assets:
  - assets/
  fonts:
  - family: Oswald
    fonts:
      - asset: assets/fonts/Oswald-Regular.ttf
