name: tank_mates
description: An aquarium compatibility app.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  flutter_spinkit: ^4.1.2
  provider: ^5.0.0
  intl: ^0.17.0
  moor: ^4.3.2
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.2
  path: ^1.8.0
  flutter_slidable: ^0.6.0
  shared_preferences: ^2.0.6
  hive: ^2.0.4
  hive_flutter: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  build_runner: ^2.0.4

flutter:
  uses-material-design: true

  assets:
  - assets/
  fonts:
  - family: Oswald
    fonts:
      - asset: assets/fonts/Oswald-Regular.ttf
